apiVersion: config.cloud.google.com/v1alpha1
kind: EdgeNodePool
metadata: # kpt-merge: config-control/site-den01-nodepool-01
  name: site-den01-nodepool-01
  namespace: config-control
spec:
  Parent Cluster: site-den01
  Node Count: '2'
  Node Location: us-central1-edge-den8
  Node Pool Location: us-central1
